/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SysAdminManagePanels;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maneesh
 */
public class ManageDileveryManPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDileveryManPanel
     */
    private EcoSystem ecoSystem;
    private JPanel userProcessContainer;
    private UserAccount userObj;
    private DeliveryMan delObj;
    public ManageDileveryManPanel(EcoSystem eco, JPanel userProcessContainer) {
        initComponents();
        this.ecoSystem = eco;
        this.userProcessContainer = userProcessContainer;
        fillTable();
    }
    
    public void fillTable(){
        ArrayList<DeliveryMan> directory = ecoSystem.getDileveryManDirectory().getDeliveryDirectory();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        
        for(DeliveryMan cust: directory){
             Object [] row = new Object[5];
             row[0] = cust.getName();
             row[1] = cust.getUserName();
             row[2] = cust.getPassword();
             row[3] = cust.getPhoneNumber();
             row[4] = cust.getAddress();
             tableModel.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 52, 244, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 101, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 96, 244, -1));

        jButton4.setText("Update Confirm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 594, -1, -1));

        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 133, -1, -1));

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 128, 244, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "User Name", "Password", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 310, 494, 272));

        jLabel6.setText("Delivery men  List");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 287, -1, -1));

        jButton1.setText("Create Dilevery Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 252, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Dilevery Men");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 11, 640, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 594, -1, -1));

        jLabel2.setText("User Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 57, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 594, -1, -1));

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 165, 244, -1));

        jLabel5.setText("Phone number");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 170, -1, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 208, 244, -1));

        jLabel7.setText("Address");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 213, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(txtAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Adress cannot be empty");
            return;
        }
        else if(txtPhoneNumber.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Phone number cannot be empty");
            return;
        }
        String regEx = "^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$";
        if (Pattern.compile(regEx).matcher(txtPhoneNumber.getText()).matches()) {
            System.out.println("yes");
        } else {
            JOptionPane.showMessageDialog(this, "Phone not in a proper format");
            return;
        }
        if(txtUserName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "User Name cannot be empty");
            return;
        }
        if(txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password cannot be empty");
            return;
        }
        if(txtName.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Name cannot be empty");
            return;
        }
        UserAccountDirectory userAccount = ecoSystem.getUserAccountDirectory();
        
        ecoSystem.getUserAccountDirectory().updateUserAccount(userObj,
                txtName.getText(), txtUserName.getText(), txtPassword.getText());
        ecoSystem.getDileveryManDirectory().updateDeliveryMan(delObj,txtName.getText(),
                txtUserName.getText(), txtPassword.getText(),
                txtPhoneNumber.getText(), txtAddress.getText());
        txtName.setText("");
        txtPassword.setText("");
        txtUserName.setText("");
                    txtAddress.setText("");
            txtPhoneNumber.setText("");
        fillTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Add new customer to the list
         if(txtAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Adress cannot be empty");
            return;
        }
        else if(txtPhoneNumber.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Phone number cannot be empty");
            return;
        }
        String regEx = "^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$";
        if (Pattern.compile(regEx).matcher(txtPhoneNumber.getText()).matches()) {
            System.out.println("yes");
        } else {
            JOptionPane.showMessageDialog(this, "Phone not in a proper format");
            return;
        }
        if(txtUserName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "User Name cannot be empty");
            return;
        }
        if(txtPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password cannot be empty");
            return;
        }
        if(txtName.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "Name cannot be empty");
            return;
        }
        UserAccountDirectory userAccount = ecoSystem.getUserAccountDirectory();
        if(userAccount.checkIfUsernameIsUnique(txtUserName.getText())){
            ecoSystem.getUserAccountDirectory().createUserAccount(txtUserName.getText(),
                txtPassword.getText(), null, new DeliverManRole());
            ecoSystem.getDileveryManDirectory().createNewDeliveryMan(txtName.getText(),
                txtUserName.getText(), txtPassword.getText(),
                txtPhoneNumber.getText(), txtAddress.getText());
            txtName.setText("");
            txtPassword.setText("");
            txtUserName.setText("");
            txtAddress.setText("");
            txtPhoneNumber.setText("");
            fillTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter a unique username");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Get selected row
        int selectedRow = jTable1.getSelectedRow();
        UserAccountDirectory userAccount = ecoSystem.getUserAccountDirectory();
        if(selectedRow >= 0){
            String username= (String) jTable1.getValueAt(selectedRow, 1);
            DeliveryMan res = ecoSystem.getDileveryManDirectory().getDeliveryMan(username);
            txtName.setText(res.getName());
            txtPassword.setText(res.getPassword());
            txtUserName.setText(res.getUserName());
            txtPhoneNumber.setText(res.getPhoneNumber());
            txtAddress.setText(res.getAddress());
            userObj=ecoSystem.getUserAccountDirectory().authenticateUser(username,
                res.getPassword());
            delObj = ecoSystem.getDileveryManDirectory().getDeliveryMan(username);
        }
        else{
            JOptionPane.showMessageDialog(this,
                "Please select one row and then press update");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow >= 0){
            String username= (String) jTable1.getValueAt(selectedRow, 1);
            String password= (String) jTable1.getValueAt(selectedRow, 2);
            userObj=ecoSystem.getUserAccountDirectory().authenticateUser(username,
                    password);
            ecoSystem.getDileveryManDirectory().deleteDeliveryMan(username);
            ecoSystem.getUserAccountDirectory().deleteUserAccount(userObj);
            fillTable();
        }
        else{
            JOptionPane.showMessageDialog(this,
                "Please select one row and then press Delete");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
