/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.mycompany.assignment1.Account;

/**
 *
 * @author maneesh
 */
public class CreateSavingAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateSavingAccountPanel
     */
    
    Account savings;
    public CreateSavingAccountPanel(Account savings) {
        initComponents();
        this.savings = savings;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRoutingNumber = new javax.swing.JTextField();
        txtAccountNumber = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        txtBalance = new javax.swing.JTextField();
        lblBankName = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        lblRoutingNumber = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblAccountBalance = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(164, 210, 164));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 95, 244, -1));
        add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 139, 244, -1));

        btnCreate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 271, 429, -1));
        add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 183, 244, -1));

        lblBankName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 60, -1, -1));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Fill Savings Account Information");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 456, -1));

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 227, 244, -1));

        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 56, 244, -1));

        lblRoutingNumber.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblRoutingNumber.setText("Routing Number");
        add(lblRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 99, -1, -1));

        lblAccountNumber.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblAccountNumber.setText("Account Number");
        add(lblAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 143, -1, -1));

        lblAccountBalance.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblAccountBalance.setText("Account Balance");
        add(lblAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 187, -1, -1));

        lblType.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblType.setText("Type");
        add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 231, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        savings.setAccountNumber(txtAccountNumber.getText());
        savings.setBalance(txtBalance.getText());
        savings.setBankName(txtBankName.getText());
        savings.setRoutingNumber(txtRoutingNumber.getText());
        savings.setType(txtType.getText());
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRoutingNumber;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
