/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.mycompany.assignment1.*;

/**
 *
 * @author maneesh
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;
    Address address;
    Account savingsAccount;
    Account checkingAccount;
    License drivingLicense;
    Medical medicalDetails;
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        workArea = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCreateAddress = new javax.swing.JButton();
        btnViewAddress = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();
        btnCreateSavingsAccount = new javax.swing.JButton();
        btnViewSavingsAccount = new javax.swing.JButton();
        btnCreateCheckingAccount = new javax.swing.JButton();
        btnViewCheckingAccount = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCreateMedical = new javax.swing.JButton();
        btnViewMedicalDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPanel.setRightComponent(workArea);

        btnCreate.setText("Create Perosnal Details");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View Personal Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnCreateAddress.setText("Create Address Details");
        btnCreateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddressActionPerformed(evt);
            }
        });

        btnViewAddress.setText("View Address Details");
        btnViewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddressActionPerformed(evt);
            }
        });

        btnViewReport.setText("View Report");
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });

        btnCreateSavingsAccount.setText("Create Savings Account");
        btnCreateSavingsAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSavingsAccountActionPerformed(evt);
            }
        });

        btnViewSavingsAccount.setText("View Savings Account");
        btnViewSavingsAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavingsAccountActionPerformed(evt);
            }
        });

        btnCreateCheckingAccount.setText("Create Checking Account");
        btnCreateCheckingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCheckingAccountActionPerformed(evt);
            }
        });

        btnViewCheckingAccount.setText("View Checking Account");
        btnViewCheckingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheckingAccountActionPerformed(evt);
            }
        });

        jButton1.setText("Create Driving Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Driving Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCreateMedical.setText("Create Medical Profile");
        btnCreateMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedicalActionPerformed(evt);
            }
        });

        btnViewMedicalDetails.setText("View Medical Details");
        btnViewMedicalDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCreate)
                        .addComponent(btnViewSavingsAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateSavingsAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnViewCheckingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateCheckingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateMedical)
                    .addComponent(btnViewMedicalDetails))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateSavingsAccount, btnViewSavingsAccount});

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnViewCheckingAccount, jButton1, jButton2});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAddress)
                .addGap(12, 12, 12)
                .addComponent(btnViewAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateSavingsAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewSavingsAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateCheckingAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCheckingAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateMedical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMedicalDetails)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        splitPanel.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(splitPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        person = new Person();
        CreatePersonPanel createPersonPanel = new CreatePersonPanel(person);
        splitPanel.setRightComponent(createPersonPanel);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ViewPersonPanel viewPersonPanel = new ViewPersonPanel(person);
        splitPanel.setRightComponent(viewPersonPanel);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCreateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddressActionPerformed
        // TODO add your handling code here:
        address = new Address();
        CreateAddressPanel addressPanel = new CreateAddressPanel(address);
        splitPanel.setRightComponent(addressPanel);
    }//GEN-LAST:event_btnCreateAddressActionPerformed

    private void btnViewAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddressActionPerformed
        // TODO add your handling code here:
        ViewAddressPanel viewAddressPanel = new ViewAddressPanel(address);
        splitPanel.setRightComponent(viewAddressPanel);
    }//GEN-LAST:event_btnViewAddressActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        // TODO add your handling code here:
        ReportScroll viewReportPanel  = new ReportScroll(person,address,savingsAccount,checkingAccount,drivingLicense,medicalDetails);
        splitPanel.setRightComponent(viewReportPanel);
    }//GEN-LAST:event_btnViewReportActionPerformed

    private void btnCreateSavingsAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSavingsAccountActionPerformed
        // TODO add your handling code here:
        savingsAccount = new Account();
        CreateSavingAccountPanel savingsPanel = new CreateSavingAccountPanel(savingsAccount);
        splitPanel.setRightComponent(savingsPanel);
    }//GEN-LAST:event_btnCreateSavingsAccountActionPerformed

    private void btnViewSavingsAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavingsAccountActionPerformed
        // TODO add your handling code here:
        ViewSavingsAccountPanel viewSavingsPanel = new ViewSavingsAccountPanel(savingsAccount);
        splitPanel.setRightComponent(viewSavingsPanel);
    }//GEN-LAST:event_btnViewSavingsAccountActionPerformed

    private void btnCreateCheckingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCheckingAccountActionPerformed
        // TODO add your handling code here:
        checkingAccount = new Account();
        CreateCheckingAccountPanel createCheckingPanel;
        createCheckingPanel = new CreateCheckingAccountPanel(checkingAccount);
        splitPanel.setRightComponent(createCheckingPanel);
    }//GEN-LAST:event_btnCreateCheckingAccountActionPerformed

    private void btnViewCheckingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheckingAccountActionPerformed
        // TODO add your handling code here:
        ViewCheckingAccountPanel viewCheckingPanel = new ViewCheckingAccountPanel(checkingAccount);
        splitPanel.setRightComponent(viewCheckingPanel);
    }//GEN-LAST:event_btnViewCheckingAccountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        drivingLicense = new License();
        CreateDrivingPanel createDrivingPanel = new CreateDrivingPanel(drivingLicense);
        splitPanel.setRightComponent(createDrivingPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ViewDrivingPanel viewDrivingPanel = new ViewDrivingPanel(drivingLicense);
        splitPanel.setRightComponent(viewDrivingPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCreateMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedicalActionPerformed
        // TODO add your handling code here:
           medicalDetails = new Medical();
        CreateMedicalPanel medicalPanel = new CreateMedicalPanel(medicalDetails);
        splitPanel.setRightComponent(medicalPanel);
    }//GEN-LAST:event_btnCreateMedicalActionPerformed

    private void btnViewMedicalDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalDetailsActionPerformed
        // TODO add your handling code here:
        ViewMedicalPanel viewMedicalPanel = new ViewMedicalPanel(medicalDetails);
        splitPanel.setRightComponent(viewMedicalPanel);
    }//GEN-LAST:event_btnViewMedicalDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateAddress;
    private javax.swing.JButton btnCreateCheckingAccount;
    private javax.swing.JButton btnCreateMedical;
    private javax.swing.JButton btnCreateSavingsAccount;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewAddress;
    private javax.swing.JButton btnViewCheckingAccount;
    private javax.swing.JButton btnViewMedicalDetails;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JButton btnViewSavingsAccount;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
