/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Models.Account;

/**
 *
 * @author maneesh
 */
public class ViewSavingsAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSavingsAccountPanel
     */
    
    Account savings;
    public ViewSavingsAccountPanel(Account savings) {
        initComponents();
        this.savings = savings;
        
        txtAccountNumber.setText(savings.getAccountNumber());
        txtBalance.setText(savings.getBalance());
        txtBankName.setText(savings.getBankName());
        txtRoutingNumber.setText(savings.getRoutingNumber());
        txtType.setText(savings.getType());
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblType = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        lblRoutingNumber = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        txtRoutingNumber = new javax.swing.JTextField();
        txtAccountNumber = new javax.swing.JTextField();
        lblAccountBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();

        setBackground(new java.awt.Color(164, 210, 164));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblType.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblType.setText("Type");
        add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 231, -1, -1));

        lblBankName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 60, -1, -1));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("View Savings Account Information");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 21, 429, -1));

        txtType.setEditable(false);
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 240, -1));

        txtBankName.setEditable(false);
        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 56, 244, -1));

        lblRoutingNumber.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblRoutingNumber.setText("Routing Number");
        add(lblRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 99, -1, -1));

        lblAccountNumber.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblAccountNumber.setText("Account Number");
        add(lblAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 143, -1, -1));

        txtRoutingNumber.setEditable(false);
        add(txtRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 95, 244, -1));

        txtAccountNumber.setEditable(false);
        add(txtAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 139, 244, -1));

        lblAccountBalance.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblAccountBalance.setText("Account Balance");
        add(lblAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 187, -1, -1));

        txtBalance.setEditable(false);
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 183, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccountBalance;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRoutingNumber;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
